version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: familyhub
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      # A gép 5432-es portját a konténer 5432-es portjára irányítjuk
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
