"""update_calendar_integration_schema

Revision ID: 080be5b3b1bb
Revises: a9ab688720ff
Create Date: 2025-09-07 23:25:49.330522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080be5b3b1bb'
down_revision: Union[str, Sequence[str], None] = 'a9ab688720ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_integrations', sa.Column('provider', sa.String(), nullable=False))
    op.add_column('calendar_integrations', sa.Column('is_enabled', sa.Boolean(), nullable=False))
    op.add_column('calendar_integrations', sa.Column('client_id', sa.String(), nullable=True))
    op.add_column('calendar_integrations', sa.Column('client_secret', sa.String(), nullable=True))
    op.add_column('calendar_integrations', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('calendar_integrations', sa.Column('calendar_url', sa.String(), nullable=True))
    op.add_column('calendar_integrations', sa.Column('sync_status', sa.String(), nullable=False))
    op.drop_column('calendar_integrations', 'sync_enabled')
    op.drop_column('calendar_integrations', 'type')
    op.drop_column('calendar_integrations', 'status')
    op.drop_column('calendar_integrations', 'external_calendar_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_integrations', sa.Column('external_calendar_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('calendar_integrations', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('calendar_integrations', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('calendar_integrations', sa.Column('sync_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('calendar_integrations', 'sync_status')
    op.drop_column('calendar_integrations', 'calendar_url')
    op.drop_column('calendar_integrations', 'token_expires_at')
    op.drop_column('calendar_integrations', 'client_secret')
    op.drop_column('calendar_integrations', 'client_id')
    op.drop_column('calendar_integrations', 'is_enabled')
    op.drop_column('calendar_integrations', 'provider')
    # ### end Alembic commands ###
