"""add_wishlist_tables

Revision ID: 1554fed0ed4e
Revises: 441a93eea0e1
Create Date: 2025-08-31 11:02:39.584838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1554fed0ed4e'
down_revision: Union[str, Sequence[str], None] = '441a93eea0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='wish_priority_enum'), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'conditional', 'modifications_requested', 'rejected', 'completed', name='wish_status_enum'), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('goal_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['goal_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishes_id'), 'wishes', ['id'], unique=False)
    op.create_table('wish_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wish_id', sa.Integer(), nullable=False),
    sa.Column('approver_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('approved', 'rejected', 'modifications_requested', 'conditional', name='approval_status_enum'), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('conditional_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wish_id'], ['wishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wish_approvals_id'), 'wish_approvals', ['id'], unique=False)
    op.create_table('wish_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wish_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('created', 'submitted', 'approved', 'rejected', 'modified', 'completed', 'deleted', name='history_action_enum'), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wish_id'], ['wishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wish_history_id'), 'wish_history', ['id'], unique=False)
    op.create_table('wish_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wish_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_order', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wish_id'], ['wishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wish_images_id'), 'wish_images', ['id'], unique=False)
    op.create_table('wish_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wish_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('link_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['wish_id'], ['wishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wish_links_id'), 'wish_links', ['id'], unique=False)
    op.drop_index(op.f('ix_debts_id'), table_name='debts')
    op.drop_table('debts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_settled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('borrower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], name=op.f('debts_borrower_id_fkey')),
    sa.ForeignKeyConstraint(['lender_id'], ['users.id'], name=op.f('debts_lender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('debts_pkey'))
    )
    op.create_index(op.f('ix_debts_id'), 'debts', ['id'], unique=False)
    op.drop_index(op.f('ix_wish_links_id'), table_name='wish_links')
    op.drop_table('wish_links')
    op.drop_index(op.f('ix_wish_images_id'), table_name='wish_images')
    op.drop_table('wish_images')
    op.drop_index(op.f('ix_wish_history_id'), table_name='wish_history')
    op.drop_table('wish_history')
    op.drop_index(op.f('ix_wish_approvals_id'), table_name='wish_approvals')
    op.drop_table('wish_approvals')
    op.drop_index(op.f('ix_wishes_id'), table_name='wishes')
    op.drop_table('wishes')
    # ### end Alembic commands ###
