"""Add goal_amount to accounts table

Revision ID: 190268999e7d
Revises: d07abf536abc
Create Date: 2025-08-22 20:25:15.776896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190268999e7d'
down_revision: Union[str, Sequence[str], None] = 'd07abf536abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('goal_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'goal_amount')
    # ### end Alembic commands ###
