"""Implement many-to-many account visibility and add goal_date

Revision ID: 298ea8b8da36
Revises: 381b9a1d97e4
Create Date: 2025-08-22 21:45:03.629070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298ea8b8da36'
down_revision: Union[str, Sequence[str], None] = '381b9a1d97e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_visibility',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'account_id')
    )
    op.drop_column('accounts', 'is_family_wide')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_family_wide', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('account_visibility')
    # ### end Alembic commands ###
