"""Add goal_date to accounts table

Revision ID: 381b9a1d97e4
Revises: 190268999e7d
Create Date: 2025-08-22 21:31:18.538517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381b9a1d97e4'
down_revision: Union[str, Sequence[str], None] = '190268999e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('goal_date', sa.Date(), nullable=True))
    op.add_column('accounts', sa.Column('is_family_wide', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'is_family_wide')
    op.drop_column('accounts', 'goal_date')
    # ### end Alembic commands ###
