"""add_synced_events_table

Revision ID: 4056d1fa67dc
Revises: 4f7815089a0c
Create Date: 2025-09-08 08:33:08.183268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4056d1fa67dc'
down_revision: Union[str, Sequence[str], None] = '4f7815089a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synced_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_integration_id', sa.Integer(), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_integration_id'], ['calendar_integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synced_events_id'), 'synced_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_synced_events_id'), table_name='synced_events')
    op.drop_table('synced_events')
    # ### end Alembic commands ###
