"""Add detailed frequency columns to recurring_rules

Revision ID: 441a93eea0e1
Revises: 5133a614bb01
Create Date: 2025-08-25 16:06:07.633792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441a93eea0e1'
down_revision: Union[str, Sequence[str], None] = '5133a614bb01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
