"""Implement detailed account visibility

Revision ID: 7e5311e84ab2
Revises: 298ea8b8da36
Create Date: 2025-08-23 15:37:47.324477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5311e84ab2'
down_revision: Union[str, Sequence[str], None] = '298ea8b8da36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('show_on_dashboard', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'show_on_dashboard')
    # ### end Alembic commands ###
