"""Add detailed frequency columns to recurring_rules

Revision ID: 7fb9716eee4f
Revises: 8c10371bf843
Create Date: 2025-09-02 11:50:22.162168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb9716eee4f'
down_revision: Union[str, Sequence[str], None] = '8c10371bf843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
