"""Add is_family_expense flag to transactions

Revision ID: 9238880ee6f8
Revises: f8a80e51784f
Create Date: 2025-08-22 16:19:21.486083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9238880ee6f8'
down_revision: Union[str, Sequence[str], None] = 'f8a80e51784f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_family_expense', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_family_expense')
    # ### end Alembic commands ###
