"""Fix deadline column in wishes

Revision ID: 9e94f38e0ce5
Revises: 8c10371bf843
Create Date: 2025-08-31 21:07:27.913428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e94f38e0ce5'
down_revision: Union[str, Sequence[str], None] = '8c10371bf843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
