"""Add detailed frequency columns to recurring_rules

Revision ID: ba14cdc13717
Revises: 348f97550cfe
Create Date: 2025-08-24 20:48:29.813638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba14cdc13717'
down_revision: Union[str, Sequence[str], None] = '348f97550cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_rules', sa.Column('day_of_week', sa.Integer(), nullable=True))
    op.add_column('recurring_rules', sa.Column('month_of_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_rules', 'month_of_year')
    op.drop_column('recurring_rules', 'day_of_week')
    # ### end Alembic commands ###
