"""add_url_and_color_fields_to_calendar_integrations

Revision ID: c3df56041a21
Revises: 9c81ee7be76f
Create Date: 2025-09-08 10:05:47.394870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3df56041a21'
down_revision: Union[str, Sequence[str], None] = '9c81ee7be76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_integrations', sa.Column('url', sa.String(), nullable=True))
    op.add_column('calendar_integrations', sa.Column('color', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_integrations', 'color')
    op.drop_column('calendar_integrations', 'url')
    # ### end Alembic commands ###
