"""Add color and icon to categories table

Revision ID: d07abf536abc
Revises: 9238880ee6f8
Create Date: 2025-08-22 16:51:42.058991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07abf536abc'
down_revision: Union[str, Sequence[str], None] = '9238880ee6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('color', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon')
    op.drop_column('categories', 'color')
    # ### end Alembic commands ###
