"""Add transfer_id to transactions table

Revision ID: f8a80e51784f
Revises: 484c9a3946a8
Create Date: 2025-08-22 14:09:30.851686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a80e51784f'
down_revision: Union[str, Sequence[str], None] = '484c9a3946a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transfer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_transactions_transfer_id'), 'transactions', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transfer_id'), table_name='transactions')
    op.drop_column('transactions', 'transfer_id')
    # ### end Alembic commands ###
